<template>
  <div class="FolderTree">
    <div class="row">
      <div class="col s12">
        <ul class="projects">
          <li class="project" 
            v-for="project in projects" 
            @click="SelectProject(project.path)">
            <h5>
              {{ project.name }}
              <a href="#" @click="remove($event, project.path)">
                <i class="fa fa-times" 
                style="float: right; margin-right: 10px;"></i>
              </a>
            </h5>
            <p>{{ project.path }}</p>
          </li>
        </ul>
      </div>
    </div>
  </div>
</template>
<script>
import EventBus from './../EventBus.js'
import _ from 'lodash'
import {remote} from 'electron'
import path from 'path'
import ProjectManager from './../core/ProjectManager.js';
let projectManager = new ProjectManager();

export default{
  name: "FolderTree",
  data(){
    return {
      projects: []
    }
  },
  methods: {
    // this method will be called if user click on a project on the left
    SelectProject(path){
      // emit this back to parent (App) so that it will
      // update the current project and the project details
      // will be rerender
      this.$emit("ProjectClicked", path);
    },
    // this method will load all the projects in the database
    LoadProjects(){
      this.projects = [];
      // get all projects in database
      let list = projectManager.getAll();
      list.forEach((project) => {
        // project name is generated by getting the folder name of the project
        project.name = _.last(project.path.split("/"));
      });
      this.projects = list;
    },
    remove(event, path){
      // remove the project from the list
      projectManager.remove({path: path});
      // reload the projects     
      this.LoadProjects();
      // stop event bubbling as it will cause the project details
      // to rerender
      event.stopPropagation();
    }
  },
  created(){
    this.LoadProjects();
    let self = this;
    // event from the parent (App)
    // this event will be sent if the user add a new project
    EventBus.$on("ProjectAdded", function(path){
      self.LoadProjects();
    });
  }
}
</script>
<style lang="scss">
.projects{
  overflow-y: scroll;
  margin-right: -20px;
  height: calc(100vh - 250px);
  &::-webkit-scrollbar-track
  {
    border-radius: 10px;
    background-color: transparent;
  }

  &::-webkit-scrollbar
  {
    width: 12px;
    background-color: transparent;
  }

  &::-webkit-scrollbar-thumb
  {
    border-radius: 10px;
    background-color: grey;
  }
}
.project{
  padding-top: 10px;
  padding-bottom: 10px;
  padding-left: 20px;
  text-overflow: ellipsis;
  &:hover{
    background: rgba(255, 255, 255, 0.1);
    cursor: pointer;
  }
  p{
    font-size: 1.1em;
  }
}
</style>