<template>
  <div class="ProjectDetails">
    <div class="row" v-if="path">
      <div class="col s12" id="TopInfo">
        <h3 class="title">
          {{ name }}
          <a href="#" @click="reload" style="font-size: 0.7em; float: right">
            <i class="fa fa-refresh" aria-hidden="true"></i>
          </a>
        </h3>
        <p class="flow-text">{{ path }}</p>
      </div>
      <div class="col s12">
        <p class="flow-text">
          Libraries
        </p>
        <div class="divider"></div>
      </div>
      <div class="col s12">
        <div id="Libraries">
          <p v-for="(library, index) in libraries">
            <input type="checkbox" 
                  :id="'lib' + index" 
                  :checked="ProjectLibraries.indexOf(library) != -1"
                  :value="library" 
                  v-model="ProjectLibraries" />
            <label :for="'lib' + index">{{ library }}</label>
          </p>
        </div>
      </div>
      <div class="col s12" style="position: fixed; bottom: 10px;">
        <a class="waves-effect waves-light btn blue" @click="save">Save</a>
      </div>
    </div>
  </div>
</template>
<script>
  import $ from 'jquery'
  import _ from 'lodash'
  import fs from 'fs'
  import path from 'path'
  import ProjectManager from './../core/ProjectManager.js';
  let projectManager = new ProjectManager();
	export default{
    name: "Project",
    props: ["path"],
    data(){
      return {
        DefaultLibraries: [], // default libraries loaded from libraries folder
        CurrentLibraries: [] // libraries loaded from the project folder
      }
    },
    computed: {
      // the name of the project
      // generated by taking the folder name
      name(){
        return _.last(this.path.split("/"))
      },
      // list of default libraries
      libraries:{
        get(){
          return this.DefaultLibraries;
        },
        set(libraries){
          this.DefaultLibraries = libraries;
        }
      }, 
      // list of project libraries
      ProjectLibraries: {
        get(){
          return this.CurrentLibraries;
        },
        set(libraries){
          this.CurrentLibraries = libraries;
        }
      }
    },
    methods: {
      // reload when user click on the reload button
      // click on the reload button the update the libraries
      // in both defaul and project libraries folder 
      reload(){
        this.libraries = fs.readdirSync(
          path.join(__static, '/libraries')
        );
        this.ProjectLibraries = fs.readdirSync(
          path.join(this.path, '/libraries')
        );
      },
      // save the project informations
      // remove necessary files or add more libraries file
      save(){
        // add more libraries
        this.ProjectLibraries.forEach((library) => {
          if(!fs.existsSync(path.join(this.path, '/libraries', library))){
            // user want to add more libraries
            fs.createReadStream(path.join(__static, '/libraries', library))
              .pipe(fs.createWriteStream(
                path.join(this.path, '/libraries', library)
              ));
          }
        });
        // remove unused libraries
        let librariesInProject = fs.readdirSync(
          path.join(this.path, '/libraries')
        );
        librariesInProject.forEach((library) => {
          if(this.ProjectLibraries.indexOf(library) == -1){
            // not needed, remove it
            fs.unlinkSync(path.join(this.path, '/libraries', library));
          }
        });
        projectManager.updateHtml(this.path, this.ProjectLibraries);
        Materialize.toast('Project saved !', 4000)
      }
    },
    watch:{
      // watch for path to change as when we click on different 
      // project on the left side panel, the path will change
      // so when it changed, make sure you load the correct libraries
      path(newPath){
        // the project folder is exists
        if(fs.existsSync(newPath)){
          this.CurrentLibraries = fs.readdirSync(
            path.join(newPath, '/libraries')
          );
          this.DefaultLibraries = fs.readdirSync(
            path.join(__static, '/libraries')
          );
        }
      }
    }
  }
</script>
<style lang="scss" scoped>
.ProjectDetails{
  height: 100vh;
  overflow: hidden;
}
#Libraries{
  overflow-y: scroll;
  // 300px is the top panel contains the info
  max-height: calc(100vh - 300px);
}
</style>